# site settings
title: Reproductions of Piers Plowman manuscripts
description: >-
  Links and bibliographic references to online and printed
  images of manuscripts of Piers Plowman.
repository: "icornelius/piers-pictures"
source: .
baseurl: "/piers-pictures" # the subpath of your site, e.g. /blog
url: "https://icornelius.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ircornelius
github_username: icornelius

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Conversion
markdown: kramdown
highlighter: rouge
incremental: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Github requirements
lsi: false
safe: true
gist:
  noscript: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
